### ISSUE TITLE
Label: Nuovi casi 

### ISSUE THREAD

**Issue by KingFelix** [LBreda/covid19_it#1]
La label "Nuovi casi" riporta tra parentesi la dicitura "nuovi positivi meno nuovi dimessi", ma il valore della colonna corrisponde esattamente ai nuovi malati. Credo che la dicitura tra parentesi vada eliminato o il dato giornaliero dovrebbe mostrare la differenza effettivamente descritta.

**Comment by LBreda** [comment]
Uhm, probabilmente devo trovare un modo migliore di spiegare le cose, se hai suggerimenti dimmi pure. Distinguo i "malati", ovvero quante persone sono malate in questo momento, dagli "infettati", ovvero quante persone sono state infettate nella storia.

I "nuovi casi" sono i nuovi malati (e forse potrei scrivere effettivamente così): li calcolo come fa la protezione civile. Ho aggiunto la nota, poiché quando il dato (per motivi vari) è stato negativo, molta gente mi ha scritto confusa "come è possibile che sono diminuiti?", ed è possibile perché la gente guarisce o muore, e può farlo più di quanto siano i nuovi casi rilevati.

**Comment by KingFelix** [comment]
Nel box in alto sostituirei la dicitura "Malati" con "Malati Attuali", mentre nel grafico metterei la dicitura "Nuovi Malati" al posto di "Nuovi Casi". Aggiungerei poi una nota sopra o sotto al grafico in cui si spieghi come i "Nuovi Malati" sono calcolati.
